[versions]
application = "8.13.0"
kotlin = "2.2.21"
compose = "2.2.21"
detekt = "1.23.8"
core-ktx = "1.17.0"
activity-compose = "1.11.0"
compose-bom = "2025.10.01"
navigation = "2.9.5"
compose-ui = "1.9.4"
material3 = "1.4.0"
appauth = "0.11.1"
browser = "1.9.0"
okhttp = "5.2.1"
gson = "2.13.2"
okio = "3.16.2"
eventbus = "3.3.1"

[plugins]
application = { id = "com.android.application", version.ref = "application" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose-ui" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
appauth = { group = "net.openid", name = "appauth", version.ref = "appauth" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
eventbus = { group = "org.greenrobot", name = "eventbus", version.ref = "eventbus" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }